export const styles = {
    main: "w-screen h-screen bg-page text-main flex overflow-hidden",
    workspace: "flex-1 min-w-0 h-full flex flex-col",
    contentShell: "flex-1 min-h-0 flex",
    body: "flex-1 min-w-0 min-h-0 bg-page",
    requestArea: "h-full bg-card",
    requestWorkspace: "h-full min-h-0 flex flex-col bg-card",
    requestTitleRow: "h-[58px] px-5 border-b border-border flex items-center justify-between shrink-0",
    requestTitle: "!text-title !text-[18px] !font-bold !leading-none",
    protocolTabs: "h-[42px] rounded-[8px] border border-border overflow-hidden flex items-center bg-card",
    protocolButton: "!h-full !px-4 !min-w-0 !rounded-none !normal-case !text-[15px] !font-medium !text-main !border-r !border-border last:!border-r-0",
    protocolActive: "!bg-[#eff5ff] !text-[#2563eb]",
    requestBar: "h-[68px] px-5 border-b border-border flex items-center gap-2 shrink-0",
    methodDropdown: "!w-[82px] !min-w-[82px] !h-[42px] !bg-[#ecfdf3] !border-none !shadow-none",
    urlInput: "h-[42px] flex-1 min-w-0 rounded-[8px] border border-border bg-soft px-4 flex items-center font-mono text-[16px] text-title",
    saveButton: "!h-[42px] !px-4 !rounded-[9px] !border !border-border !bg-card !text-title !normal-case !text-[15px] !font-semibold !shadow-none",
    sendButton: "!h-[42px] !px-5 !rounded-[9px] !bg-pri-500 !text-white !normal-case !text-[15px] !font-semibold !shadow-none",
    editorResponseGrid: "flex-1 min-h-0 grid grid-cols-[minmax(520px,708px)_1fr]",
    editorPane: "min-h-0 border-r border-border bg-card flex flex-col",
    requestTabRow: "h-[45px] px-4 border-b border-border flex items-center gap-8 shrink-0",
    requestTab: "h-full flex items-center gap-1 text-[15px] font-medium text-main border-b-2 border-transparent",
    requestTabActive: "text-pri-500 border-pri-500",
    tabCount: "w-[20px] h-[20px] rounded-full bg-soft text-sub text-[12px] font-semibold flex items-center justify-center",
    bodyTypeRow: "h-[54px] px-5 flex items-center gap-4 shrink-0 bg-page",
    bodyType: "flex items-center gap-2 text-main",
    radioDot: "w-[10px] h-[10px] rounded-full bg-[#4b5563]",
    radioDotActive: "border-[3px] border-pri-600 bg-card",
    bodyTypeText: "!text-[15px] !font-medium !text-main !leading-none",
    codeEditor: "mx-5 mb-3 flex-1 min-h-0 rounded-[8px] border border-border overflow-hidden bg-card",
    codeHeader: "h-[33px] px-3 border-b border-border bg-card flex items-center justify-between",
    codeTitle: "!text-[14px] !font-bold !tracking-wide !text-main",
    codeActions: "flex items-center gap-2 text-[13px] font-medium text-main",
    codeBlock: "h-full p-5 bg-card",
    codeText: "!m-0 font-mono !text-[15px] !leading-7 !text-title",
    responsePane: "min-h-0 bg-page flex flex-col items-center justify-center text-center",
    emptyIcon: "!text-pri-300 !text-[38px] mb-4 rotate-[42deg]",
    emptyTitle: "!text-title !text-[18px] !font-semibold !leading-none",
    emptySub: "!text-main !text-[15px] !font-medium !mt-3"
}
